import type { Lead } from '../types/lead'
import type { Property } from '../types/property'

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Sophie Martin',
    email: 'sophie.martin@gmail.com',
    phone: '06 12 34 56 78',
    status: 'nouveau',
    propertyId: '1',
    propertyTitle: 'Appartement 3P — 11e',
    createdAt: '2026-04-10',
    budget: 480000,
    source: 'SeLoger',
    notes: 'Cherche un bien spacieux avec balcon. Disponible les week-ends pour les visites.',
  },
  {
    id: '2',
    name: 'Marc Dupont',
    email: 'marc.dupont@gmail.com',
    phone: '06 98 76 54 32',
    status: 'En contact',
    propertyId: '2',
    propertyTitle: 'Maison — Massy',
    createdAt: '2026-04-11',
    budget: 400000,
    source: 'LeBonCoin',
    notes: 'Famille avec 2 enfants, cherche jardin. Préfère le RDC ou 1er étage.',
    visitDate: '2026-04-20',
  },
  {
    id: '3',
    name: 'Laura Bernard',
    email: 'laura.bernard@gmail.com',
    phone: '07 11 22 33 44',
    status: 'visite',
    propertyId: '1',
    propertyTitle: 'Appartement 3P — 11e',
    createdAt: '2026-04-12',
    budget: 460000,
    source: 'Recommandation',
    notes: 'Très intéressée, a visité 2 fois. Attend le retour de son banquier.',
    visitDate: '2026-04-18',
  },
  {
    id: '4',
    name: 'Pierre Lefranc',
    email: 'pierre.lefranc@gmail.com',
    phone: '06 55 44 33 22',
    status: 'offre',
    propertyId: '3',
    propertyTitle: 'Loft — 3e',
    createdAt: '2026-04-13',
    budget: 640000,
    source: 'Site web',
    notes: 'Offre à 610 000 € déposée. En attente de la réponse du vendeur.',
    visitDate: '2026-04-15',
  },
  {
    id: '5',
    name: 'Camille Roux',
    email: 'camille.roux@gmail.com',
    phone: '06 77 88 99 00',
    status: 'nouveau',
    propertyId: '2',
    propertyTitle: 'Maison — Massy',
    createdAt: '2026-04-14',
    budget: 390000,
    source: 'SeLoger',
    notes: 'Premier achat. Cherche à être proche des transports en commun.',
  },
]

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Appartement 3P — 11e',
    address: '24 rue de la Roquette, Paris 11e',
    price: 450000,
    status: 'available',
    leadsCount: 3,
  },
  {
    id: '2',
    title: 'Maison — Massy',
    address: '12 avenue de la République, Massy',
    price: 380000,
    status: 'under_offer',
    leadsCount: 2,
  },
  {
    id: '3',
    title: 'Loft — 3e',
    address: '8 rue du Temple, Paris 3e',
    price: 620000,
    status: 'available',
    leadsCount: 1,
  },
  {
    id: '4',
    title: 'Studio — 6e',
    address: '3 rue de Vaugirard, Paris 6e',
    price: 210000,
    status: 'sold',
    leadsCount: 0,
  },
]

export const mockKpis = {
  activeLeads: 24,
  availableProperties: 18,
  visitsThisWeek: 7,
  pendingOffers: 3,
}

export const mockRecentLeads = [
  {
    id: '1',
    name: 'Sophie Martin',
    status: 'nouveau',
    propertyTitle: 'Appartement 3P — 11e',
    createdAt: '2026-04-15',
  },
  {
    id: '2',
    name: 'Marc Dupont',
    status: 'En contact',
    propertyTitle: 'Maison — Massy',
    createdAt: '2026-04-14',
  },
  {
    id: '3',
    name: 'Laura Bernard',
    status: 'visite',
    propertyTitle: 'Studio — 6e',
    createdAt: '2026-04-13',
  },
  {
    id: '4',
    name: 'Pierre Lefranc',
    status: 'offre',
    propertyTitle: 'Loft — 3e',
    createdAt: '2026-04-12',
  },
  {
    id: '5',
    name: 'Camille Roux',
    status: 'nouveau',
    propertyTitle: 'Appartement 2P — 14e',
    createdAt: '2026-04-11',
  },
]

export const mockPropertiesDetail: Property[] = [
  {
    id: '1',
    title: 'Appartement 3P — 11e',
    address: '24 rue de la Roquette, Paris 11e',
    price: 450000,
    status: 'available',
    leadsCount: 3,
    image: require('../../assets/images/properties/appart1.jpeg'),
    surface: 72,
    rooms: 3,
    type: 'Appartement',
    description:
      'Bel appartement lumineux au 3e étage avec ascenseur. Double exposition, parquet en chêne, cuisine équipée. Proche métro Voltaire.',
  },
  {
    id: '2',
    title: 'Maison — Massy',
    address: '12 avenue de la République, Massy',
    price: 380000,
    status: 'under_offer',
    leadsCount: 2,
    image: require('../../assets/images/properties/maison1.jpeg'),
    surface: 110,
    rooms: 5,
    type: 'Maison',
    description:
      'Maison de ville avec jardin de 80 m². Garage, cave, 4 chambres. Secteur calme, à 5 min du RER B.',
  },
  {
    id: '3',
    title: 'Loft — 3e',
    address: '8 rue du Temple, Paris 3e',
    price: 620000,
    status: 'available',
    leadsCount: 1,
    image: require('../../assets/images/properties/loft1.jpeg'),
    surface: 95,
    rooms: 2,
    type: 'Loft',
    description:
      'Loft d\'exception en plein Marais. Hauteur sous plafond 3,5 m, verrières industrielles, cuisine ouverte haut de gamme.',
  },
  {
    id: '4',
    title: 'Studio — 6e',
    address: '3 rue de Vaugirard, Paris 6e',
    price: 210000,
    status: 'sold',
    leadsCount: 0,
    image: require('../../assets/images/properties/appart2.jpeg'),
    surface: 28,
    rooms: 1,
    type: 'Studio',
    description:
      'Studio idéalement situé au cœur de Saint-Germain-des-Prés. Entièrement rénové, immeuble haussmannien.',
  },
]
