export const mockLeads = [
  {
    id: '1',
    name: 'Sophie Martin',
    email: 'sophie.martin@gmail.com',
    phone: '06 12 34 56 78',
    status: 'new',
    propertyId: '1',
    propertyTitle: 'Appartement 3P — 11e',
    createdAt: '2026-04-10',
  },
  {
    id: '2',
    name: 'Marc Dupont',
    email: 'marc.dupont@gmail.com',
    phone: '06 98 76 54 32',
    status: 'contacted',
    propertyId: '2',
    propertyTitle: 'Maison — Massy',
    createdAt: '2026-04-11',
  },
  {
    id: '3',
    name: 'Laura Bernard',
    email: 'laura.bernard@gmail.com',
    phone: '07 11 22 33 44',
    status: 'visiting',
    propertyId: '1',
    propertyTitle: 'Appartement 3P — 11e',
    createdAt: '2026-04-12',
  },
  {
    id: '4',
    name: 'Pierre Lefranc',
    email: 'pierre.lefranc@gmail.com',
    phone: '06 55 44 33 22',
    status: 'offer',
    propertyId: '3',
    propertyTitle: 'Loft — 3e',
    createdAt: '2026-04-13',
  },
  {
    id: '5',
    name: 'Camille Roux',
    email: 'camille.roux@gmail.com',
    phone: '06 77 88 99 00',
    status: 'new',
    propertyId: '2',
    propertyTitle: 'Maison — Massy',
    createdAt: '2026-04-14',
  },
]

export const mockProperties = [
  {
    id: '1',
    title: 'Appartement 3P — 11e',
    address: '24 rue de la Roquette, Paris 11e',
    price: 450000,
    status: 'available',
    leadsCount: 3,
  },
  {
    id: '2',
    title: 'Maison — Massy',
    address: '12 avenue de la République, Massy',
    price: 380000,
    status: 'under_offer',
    leadsCount: 2,
  },
  {
    id: '3',
    title: 'Loft — 3e',
    address: '8 rue du Temple, Paris 3e',
    price: 620000,
    status: 'available',
    leadsCount: 1,
  },
  {
    id: '4',
    title: 'Studio — 6e',
    address: '3 rue de Vaugirard, Paris 6e',
    price: 210000,
    status: 'sold',
    leadsCount: 0,
  },
]

export const mockKpis = {
  activeLeads: 5,
  availableProperties: 2,
  visitsThisWeek: 3,
  pendingOffers: 1,
}